Fix example in README.md (#410)
* Fix example in README.md

The minimal example was missing the wrapping `disko.devices` attributes which resulted in the following error message:

```
error: attribute 'disko' missing

       at /nix/store/1lvj5ry4y5qyis40qcch1csf8h86z8bk-disko/share/disko/default.nix:10:49:

            9|       # _file = toString input;
           10|       imports = lib.singleton { disko.devices = cfg.disko.devices; };
             |                                                 ^
           11|       options = {
       Did you mean disk?
```

* Increase ESP size

From 100M to 500M

Co-authored-by: Jörg Thalheim <Mic92@users.noreply.github.com>

---------

Co-authored-by: Jörg Thalheim <Mic92@users.noreply.github.com>