flake: export lib with references to nixpkgs input
This previously pointed at `<nixpkgs/...>`, which might be anything. It
caused this error for me, when I tried to use `lib.makeDiskoTest`
downstream:

  error: cannot look up '<nixpkgs/nixos/tests/make-test-python.nix>' in
  pure evaluation mode (use '--impure' to override)